import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Navbar from '../../components/Navbar'
import PleaseLogin from '../../components/PleaseLogin'
import UpdatesForYou from '../../components/UpdatesForYou'
import CreateUpdate from '../../components/CreateUpdate'
import DeleteUpdate from '../../components/DeleteUpdate'
import UpdateUpdate from '../../components/UpdateUpdate'
import styles from '../../styles/Home.module.css'
import { getAuthToken } from '../../service/auth/auth.service';
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [islogin, setIslogin] = useState(false);
  const router = useRouter();

  const content = () =>{
    if(islogin){
      return(
        <div>
          <UpdatesForYou/>
          <CreateUpdate/>
          <DeleteUpdate/>
          <UpdateUpdate/>
        </div>
      )
    }
    else{
      return(
        <PleaseLogin/>
      )
    }

  }
  useEffect(()=>{
    const jwtToken = getAuthToken();
    if (jwtToken !== null) {
      setIslogin(true);
    } else {
      setIslogin(false)
    }

    // const token = localStorage.getItem('token');
    // if(!token){
    //   // router.push('/signin');
    //   setIslogin(false)
    // } else {
    //   setIslogin(true);
    // }
  }), [];

  return (
    <div className={styles.container}>
      <Head>
        <title>New Console</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
      <div>
        <Navbar/>
        {content()}
      </div>
    </div>
    
  )
}

export default Home
