import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Navbar from '../components/Navbar'
import PleaseLogin from '../components/PleaseLogin'
import UpdatesForYou from '../components/UpdatesForYou'
import CreateUpdate from '../components/CreateUpdate'
import DeleteUpdate from '../components/DeleteUpdate'
import UpdateUpdate from '../components/UpdateUpdate'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [islogin, setIslogin] = useState(false);
  const content = () =>{
    if(islogin){
      return(
        <div>
          <UpdatesForYou/>
          <CreateUpdate/>
          <DeleteUpdate/>
          <UpdateUpdate/>
        </div>
      )
    }
    else{
      return(
        <div>
          <PleaseLogin/>
        </div>
      )
    }

  }
  useEffect(()=>{
    const token = localStorage.getItem('token');
    if(!token){
      // router.push('/signin');
      setIslogin(false)
    } else {
      setIslogin(true);
    }
  }), [];

  return (
    <div className={styles.container}>
      <Head>
        <title>New Console</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
      <div>
        <Navbar/>
        {content()}
      </div>
    </div>
    
  )
}

export default Home
